version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: absensi_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: attendance_kpi
      MYSQL_USER: absensi_user
      MYSQL_PASSWORD: absensi123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - absensi_network

  # PHPMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: absensi_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - mysql
    networks:
      - absensi_network

  # Laravel Backend (optional - bisa jalan di host)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: absensi_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: attendance_kpi
      DB_USERNAME: absensi_user
      DB_PASSWORD: absensi123
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      - absensi_network

volumes:
  mysql_data:

networks:
  absensi_network:
    driver: bridge
