name: attendance_kpi_mobile
description: Modern attendance and KPI management mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0
  
  # State Management
  provider: ^6.0.5
  
  # HTTP & API
  dio: ^5.3.2
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  # google_maps_flutter: ^2.5.0
  
  # Camera & Images
  image_picker: ^1.0.4
  # camera: ^0.10.5+5
  
  # QR Code
  # mobile_scanner: ^3.5.6
  
  # Biometric
  # local_auth: ^2.1.6
  
  # Utils
  intl: ^0.18.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  # flutter_local_notifications: ^13.0.0
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
